import Link from "next/link"
import { Calendar, Tag } from "lucide-react"
import { getAllPosts } from "@/lib/blog"
import { localeTags, type Locale } from "@/lib/i18n"
const copy: Record<Locale, { eyebrow: string; title: string; description: string; read: string; empty: string }> = {
  pt: { eyebrow: "Blog", title: "Engenharia de software aplicada", description: "Notas técnicas sobre arquitetura, produtos digitais, IA e entrega de software.", read: "Ler artigo", empty: "Nenhum post publicado ainda." },
  en: { eyebrow: "Blog", title: "Applied software engineering", description: "Technical notes on architecture, digital products, AI, and software delivery.", read: "Read article", empty: "No posts published yet." },
  es: { eyebrow: "Blog", title: "Ingeniería de software aplicada", description: "Notas técnicas sobre arquitectura, productos digitales, IA y entrega de software.", read: "Leer artículo", empty: "Aún no hay publicaciones." },
}
export function BlogIndex({ locale }: { locale: Locale }) {
  const posts = getAllPosts(locale); const text = copy[locale]
  return <div className="py-24" lang={localeTags[locale]}><section className="relative overflow-hidden bg-gradient-to-br from-primary/10 via-background to-background"><div className="container mx-auto px-4 py-16 text-center"><p className="text-sm font-medium text-primary">{text.eyebrow}</p><h1 className="mx-auto mt-4 max-w-3xl text-4xl font-bold md:text-5xl">{text.title}</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-muted-foreground">{text.description}</p></div></section><section className="container mx-auto px-4 py-16" aria-label={text.eyebrow}>{posts.length === 0 ? <p className="text-muted-foreground">{text.empty}</p> : <div className="grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-3">{posts.map(post => <article key={post.slug} className="flex h-full flex-col rounded-2xl border border-border/60 bg-background p-6 shadow-sm"><time dateTime={post.date} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><Calendar className="h-4 w-4" aria-hidden="true" />{new Intl.DateTimeFormat(localeTags[locale], { dateStyle: "long", timeZone: "UTC" }).format(new Date(post.date))}</time><h2 className="mt-4 text-2xl font-semibold leading-snug"><Link href={post.url} className="hover:text-primary">{post.title}</Link></h2><p className="mt-3 text-muted-foreground">{post.excerpt}</p><ul className="mt-6 flex flex-wrap gap-2" aria-label="Tags">{post.tags.map(tag => <li key={tag} className="inline-flex items-center gap-1 rounded-full bg-secondary px-3 py-1 text-xs font-medium"><Tag className="h-3 w-3" aria-hidden="true" />{tag}</li>)}</ul><Link href={post.url} className="mt-auto pt-6 text-sm font-semibold text-primary underline underline-offset-4">{text.read}</Link></article>)}</div>}</section></div>
}
